version: "3.7"

services:
  web:
    container_name: web
    # env_file: ./.env
    build: ./backend/.
    volumes:
      - ./backend/:/backend/
      - static_volume:/backend/static # <-- bind the static volume
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 backend.wsgi:application
    networks:
      - backend_network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend:
    container_name: wb-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/wb-frontend
      - ./frontend/node_modules/:/wb-frontend/node_modules

  backend-server:
    container_name: nginx-back
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    volumes:
      - static_volume:/backend/static # <-- bind the static volume
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - backend_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - web
    networks:
      - backend_network
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3333:3000
    depends_on:
      - prometheus
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: "rabbitmq"
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
    expose:
      - 5672
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - web
    networks:
      - backend_network
    tty: true

  celery:
    container_name: celery_service
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    command: >
      bash -c "celery -A backend worker --loglevel=info --pool=solo"
    networks:
      - backend_network
    depends_on:
      - web
      - rabbitmq
    tty: true

networks:
  backend_network:
    driver: bridge
volumes:
  static_volume:
  # 인스턴스에 대해 데이터를 영구적으로 유지하기 위해 2개의 볼륨 사용
  prometheus_data: {}
  grafana_data: {}
