groups:
- name: alert
  rules:
  - alert: ErrorStatusAndFailRate
    expr: | 
      sum(rate(nginx_http_response_count_total{status=~"2.."}[1m])) >= 1
      and
      (
        sum(rate(nginx_http_response_count_total{status=~"2.."}[1m])) 
        / 
        sum(rate(nginx_http_response_count_total[1m])) * 100
      ) >= 50
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: 'Error Status Code Bigger than 10 And Fail Rate Higher than 50%'